services:
  tiktok-uploader:
    build: .
    ports:
      - "5900:5900"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./cookies.txt:/app/cookies.txt
      - ./localStorage.json:/app/localStorage.json
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file:
      - .env
    restart: "no"
    tty: true
    stdin_open: true
